@startuml

title __DAO's Class Diagram__\n

  namespace Dao {
    class Dao.AES {
        {static} - key : byte[]
        {static} - secretKey : SecretKeySpec
        {static} + decrypt()
        {static} + encrypt()
        {static} + setKey()
    }
  }
  

  namespace Dao {
    class Dao.BottleTypeDao {
        + AddBottleType()
        + getBottleType()
    }
  }
  

  namespace Dao {
    class Dao.BottlesDao {
        + AddBottle()
        + get187Bottles()
        + get200Bottles()
        + get375Bottles()
        + get750Bottles()
        + getBottles()
        + getBottlesMaxID()
    }
  }
  

  namespace Dao {
    class Dao.CurrentStockDao {
        + AddRecord()
        + DeleteRecord()
        + cur187Bottles()
        + cur200Bottles()
        + cur375Bottles()
        + cur750Bottles()
        + curRedGrape()
        + curWhiteGrape()
        + getLatestRecordID()
        + getRecordByID()
        + getRecords()
    }
  }
  

  namespace Dao {
    class Dao.GrapeDao {
        + AddGrape()
        + getGrape()
        + getMaxID()
        + getRedGrape()
        + getWhiteGrape()
    }
  }
  

  namespace Dao {
    class Dao.GrapeTypeDao {
        + AddGrapeType()
        + getGrapeType()
    }
  }
  

  namespace Dao {
    class Dao.HibernateUtil {
        {static} + sessionFactory : SessionFactory
        {static} + getSessionFactory()
    }
  }
  

  namespace Dao {
    class Dao.NotificationsDao {
        + AddNotification()
        + DeleteNotification()
        + UpdateNotification()
        + getMaxID()
        + getNotifications()
    }
  }
  

  namespace Dao {
    class Dao.PrivilegeTypeDao {
        + AddPrivilege()
        + getPrivilegeType()
    }
  }
  

  namespace Dao {
    class Dao.UsersDao {
        {static} + loggedid : int
        + AddUser()
        + DeleteUser()
        + UpdateUser()
        + getLoggedid()
        + getMaxID()
        + getUserByUsername()
        + getUsers()
        + setLoggedid()
    }
  }
  

  namespace Dao {
    class Dao.WarehouseDao {
        + AddWarehouse()
        + getWarehouses()
    }
  }
  

  namespace Dao {
    class Dao.WineDao {
        + AddWine()
        + getMaxID()
        + getWine()
    }
  }
  

  namespace Dao {
    class Dao.WineTypeDao {
        + AddWineType()
        + DeleteWineType()
        + UpdateWineType()
        + getMaxID()
        + getWineType()
        + getWineTypeByUserID()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
